### ISSUE TITLE
Domino server crash after DirectoryScanner run

### ISSUE THREAD

**Issue by eknori001** [klehmann/domino-jna#16]
Server is Domino 9.0.1/64 FP9 on Win

The last update from 04-JAN-2017 does not crash the server right after DOTS start. But I am still having problems when running DirectoryScanner .

here is the stripped down code that I use 

```
public class ScannerManager extends BaseJNA {
    
	private List<SearchResultData>	searchResultData;
	private ConfigProvider			configProvider		= ConfigProvider.getInstance();

	public void run() {
		runWithSession(new IDominoCallable<Object>() {

			@Override
			public Object call(Session session) throws Exception {

				try {
					if (configProvider.isUpdateExecutor()) {
						ServerTaskManager.getInstance().logMessageText(strTask + Constants.TASK_ACTIVITY_PROCESSING);

						configProvider.getConfiguredServers();

						DirectoryScanner scanner = null;

						for (Server server : configProvider.getServersList()) {
							scanner = new DirectoryScanner(server.getServerName(), null,
							        EnumSet.of(FileType.ANYNOTEFILE, FileType.RECURSE));
							searchResultData = scanner.scan();

							ServerTaskManager.getInstance()
							        .logMessageText(strTask + String.format(" App count: %d", searchResultData.size()));
							scanner = null;
						}
						ServerTaskManager.getInstance().logMessageText(strTask + Constants.TASK_ACTIVITY_FINISHED);
					}
				} catch (Exception e) {
					e.printStackTrace();
				}
				return null;
			}
		});
	}
} 
```

Here is what happens on the console

> te dots apptool scanner run
> 
> [0EFC:0002-1818] 01/05/2018 07:44:35 AM  [DOTS] application.tool - Scanner Task processing ...
> [0EFC:0002-1818] 01/05/2018 07:44:39 AM  [DOTS] application.tool - Scanner Task App count: 182
> [0EFC:0002-1818] 01/05/2018 07:44:42 AM  [DOTS] application.tool - Scanner Task App count: 162
> [0EFC:0002-1818] 01/05/2018 07:44:42 AM  [DOTS] application.tool - Scanner Task finished.

Then, after 30 seconds the server goes down. No evidence on the console, what is going wrong.

The NSD only gives some vague hint about an unhandled exception and that DOTS terminated abnormally.

> 
> @[ 8] 0x7FF9FE050657 nnotes.OSNTUnhandledExceptionFilter+423 (13b8a7b0,7FF9FF50E630,13b8d810,13b8a4f6)
> 
>        Parameter 1:
>             13b8a7b0 30A8B813 00000000 00000000 00000000 | 0... .... .... .... |
>             13b8a7c0 00000000 00000000 00000000 00000000 | .... .... .... .... |
> 
> 
>        Parameter 2:
>             ff50e630 50414E49 433A2025 73000000 00000000 | PANI C: % s... .... |
>             ff50e640 4E4F5445 535F4150 49444556 00000000 | NOTE S_AP IDEV .... |
> 
> 
>        Parameter 3:
>             13b8d810 50726F63 65737320 433A5C50 726F6772 | Proc ess  C:\P rogr |
>             13b8d820 616D2046 696C6573 5C49424D 5C446F6D | am F iles \IBM \Dom |
>             13b8d830 696E6F5C 6E646F74 732E4558 45202833 | ino\ ndot s.EX E (3 |
>             13b8d840 3833362F 30784546 43292068 61732074 | 836/ 0xEF C) h as t |
>             13b8d850 65726D69 6E617465 64206162 6E6F726D | ermi nate d ab norm |
>             13b8d860 616C6C79 00000000 0A000200 00000000 | ally .... .... .... |
> 
> 
>        Parameter 4:
>             13b8a4f6 00000000 0000                       | .... ..             |
>             13b8a4fc 00000000 39E650FF F97F0000 38E650FF | .... 9.P. .... 8.P. |
>             13b8a50c F97F0000 29C98803 0000              | .... )... ..        |
> 
> @[ 9] 0x7FF9FDFED227 nnotes.Panic+1047 (efc,125820C00252535,13b8d8e0,e)
>

**Comment by eknori001** [comment]
UPDATE:
seems to be DOTS related. If I let run the code scheduled, it runs without crashing the server. 

when using the **te dots apptool scanner run** command then the crash is reproducible

```
public class Commands implements CommandProvider {

	public void _apptool(CommandInterpreter ci) { 
		String strCommand = ci.nextArgument();
		try {
			if (strCommand == null || "help".equalsIgnoreCase(strCommand)) {
				ci.print(getHelp());
			} else if ("loglevel".equalsIgnoreCase(strCommand)) {
				String strLogLevel = ci.nextArgument();
				Log.getInstance();
				Log.setLogLevel(strLogLevel);
			} else if ("info".equalsIgnoreCase(strCommand)) {
				getPluginInfo();
			}

			else if ("scanner".equalsIgnoreCase(strCommand)) {
				String action = ci.nextArgument();
				if ("suspend".equalsIgnoreCase(action)) {
					ConfigProvider.getInstance().setSuspendScanner(true);
				} else if ("resume".equalsIgnoreCase(action)) {
					ConfigProvider.getInstance().setSuspendScanner(false);
				} else if ("run".equalsIgnoreCase(action)) {
					ScannerManager scannerManager = new ScannerManager();
					scannerManager.run();
				} else {
					ci.print(getHelp());
				}
```

**Comment by klehmann** [comment]
Sounds a bit like this FAQ:
https://github.com/java-native-access/jna/blob/master/www/FrequentlyAskedQuestions.md#why-does-the-vm-sometimes-crash-in-my-shutdown-hook-on-windows

Does the same code run without crash on Linux?

What you could try is call com.mindoo.domino.jna.gc.NotesGC.setLogCrashingThreadStacktrace(true).

This writes the stacktrace of the current call stack to a file "domino-jna-stack-*.txt" in the temp folder before any native code execution and makes sure that all the disk cache is flushed.

See com.mindoo.domino.jna.internal.NotesNativeAPI.MethodInterceptorWithStacktraceLogging.createStackTraceFile(Exception) for details.

I will try to reproduce this on my machine. What's in your BaseJNA class?

**Comment by eknori001** [comment]
Have not yet tried on LINUX.  will do and report later.

BaseJNA is 

```
import java.util.concurrent.Callable;

import com.mindoo.domino.jna.gc.NotesGC;
import com.mindoo.domino.jna.internal.NotesNativeAPI;
import com.mindoo.domino.jna.utils.NotesInitUtils;

import lotus.domino.NotesException;
import lotus.domino.NotesFactory;
import lotus.domino.NotesThread;
import lotus.domino.Session;

public class BaseJNA {

	private static boolean			mNotesInitExtendedCalled	= false;
	private ThreadLocal<Session>	mThreadSession				= new ThreadLocal<Session>();

	public static void initNotes() {
		NotesNativeAPI.initialize();
		String notesProgramDir = System.getenv("Notes_ExecDirectory");
		String notesIniPath = System.getenv("NotesINI");

		if (notesProgramDir != null && notesProgramDir.length() > 0 && notesIniPath != null
		        && notesIniPath.length() > 0) {
			NotesInitUtils.notesInitExtended(new String[] { notesProgramDir, "=" + notesIniPath });
			mNotesInitExtendedCalled = true;
		}
		NotesThread.sinitThread();
	}

	public static void termNotes() {
		if (mNotesInitExtendedCalled) {
			NotesInitUtils.notesTerm();
		}
		NotesThread.stermThread();
	}

	public Session getSession() {
		return mThreadSession.get();
	}

	public <T> T runWithSession(final IDominoCallable<T> callable) {
		final Session[] session = new Session[1];
		try {
			session[0] = NotesFactory.createSession();
			session[0].setTrackMillisecInJavaDates(true);
			mThreadSession.set(session[0]);

			T result = NotesGC.runWithAutoGC(new Callable<T>() {

				@Override
				public T call() throws Exception {
					T result = callable.call(session[0]);
					return result;
				}
			});
			return result;
		} catch (Throwable e) {
			throw new RuntimeException(e);
		} finally {
			if (session[0] != null) {
				try {
					session[0].recycle();
				} catch (NotesException e) {
					e.printStackTrace();
				}
			}
			mThreadSession.set(null);
		}
	}

	public static interface IDominoCallable<T> {

		public T call(Session session) throws Exception;

	}
}
```

**Comment by eknori001** [comment]
I added a line of code to my application, rebuild the app and deployed it to my server.
I have no idea why, but now it runs stable. no more crash.

I will close this issue for now as "MIRACLE"
