### ISSUE TITLE
encoding issue of Chinese

### ISSUE THREAD

**Issue by kenizhou** [klehmann/domino-jna#22]
Thank you very much for your amazing contribution.

I encounter an encoding issue when extract mailbody as HTML , all  Chinese characters display as question marks("??????").

is this library not support non-English languages?

Thanks!

**Comment by klehmann** [comment]
In should support non-English languages, at least I am often testing it with German Umlauts and using it in production at several German customers. Is this only a richtext-HTML conversion issue or do you have issues with Chinese characters in text items as well?
Could you send me an example mail to "karsten.lehmann(at)mindoo.de"?

**Comment by klehmann** [comment]
I just checked it but and the conversion seems to be correct.

Here is my sample code:

```java
package com.mindoo.domino.jna.test;

import java.io.File;
import java.io.FileOutputStream;
import java.io.OutputStreamWriter;
import java.util.EnumSet;
import java.util.List;
import java.util.Map;
import java.util.concurrent.atomic.AtomicInteger;

import org.junit.Test;

import com.mindoo.domino.jna.NotesDatabase;
import com.mindoo.domino.jna.NotesNote;
import com.mindoo.domino.jna.NotesNote.HtmlConvertOption;
import com.mindoo.domino.jna.html.IHtmlConversionResult;
import com.mindoo.domino.jna.html.IHtmlImageRef;
import com.mindoo.domino.jna.html.ReferenceType;
import com.mindoo.domino.jna.html.TargetType;

import lotus.domino.Session;

/**
 * Tests cases for HTML conversion of richtext
 * 
 * @author Karsten Lehmann
 */
public class TestHtmlAPI extends BaseJNATestClass {

	@Test
	public void testRichtextHtmlConversion() {
		runWithSession(new IDominoCallable<Object>() {

			@Override
			public Object call(Session session) throws Exception {
				NotesDatabase db = new NotesDatabase(session, "Server1/Mindoo", "mail/klehmann.nsf");
				NotesNote note = db.openNoteByUnid("0B943067F058096AC12582DE0033D8FE");
				
				EnumSet<ReferenceType> refTypeFilter = null;
				Map<ReferenceType,EnumSet<TargetType>> targetTypeFilter = null;
				
				IHtmlConversionResult convResult = note.convertItemToHtml("Body", EnumSet.allOf(HtmlConvertOption.class),
						refTypeFilter, targetTypeFilter);
				String html = convResult.getText();
				System.out.println("HTML:\n"+html);

				List<IHtmlImageRef> images = convResult.getImages();
				
				File htmlOutDir = new File("/tmp");
				htmlOutDir.mkdirs();
				
				final AtomicInteger imgIdx = new AtomicInteger();

				for (IHtmlImageRef currImage : images) {
					String currRefTxt = currImage.getReferenceText();
					System.out.println("Image ref text: "+currRefTxt);
					
					File imgFile = new File(htmlOutDir, "img"+imgIdx+"."+currImage.getFormat());
					currImage.writeImage(imgFile);
					html = html.replace(currRefTxt, imgFile.getName());
					imgIdx.incrementAndGet();
				}
				
				File htmlFile = new File(htmlOutDir, "index.html");
				if (htmlFile.exists())
					htmlFile.delete();
				
				FileOutputStream fOut = new FileOutputStream(htmlFile);
				OutputStreamWriter outWriter = new OutputStreamWriter(fOut, "UTF-8");
				outWriter.write("<html><head><meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" /></head>");
				outWriter.write("<body>");
				outWriter.write(html);
				outWriter.write("</body></html>");
				outWriter.close();
				
				return null;
			}
		});
	}
	
}
```

I send a Notes mail to myself with this sample text:
今天天氣太嚴熱了！

<img width="378" src="https://user-images.githubusercontent.com/4291861/43635826-96535714-9710-11e8-837f-ffa8286053fa.png">

When I run the sample code, the result looks ok in console and browser:

<img width="766" src="https://user-images.githubusercontent.com/4291861/43635924-e1078e42-9710-11e8-951f-1a9f1b000aed.png">

**Comment by klehmann** [comment]
Also tested with a MIME mail - same result.

**Comment by kenizhou** [comment]
thank you for your quick response.

I find the root cause:  in NotesNote.java->internalConvertItemToHtml();

Each buffer block is 256 bytes, for English it is perfect, because 1 byte represents 1 character, but for Chinese one character needs 3 bytes.  so every 85 chinese characters there is one garbage character. 


 

![image](https://user-images.githubusercontent.com/614477/43670904-3ae59860-97c4-11e8-9275-be0cff25385b.png)



![untitled](https://user-images.githubusercontent.com/614477/43671028-e683aa8a-97c5-11e8-9ed0-4633774fcf70.gif)

**Comment by kenizhou** [comment]
after reviewing my initial question, I would like correct it:  the question mark issue is my encoding fault,  the real problem is described in the last post.

**Comment by kenizhou** [comment]
Thank you very much  for you fixing.

 I have done the testing it works fine now.  I do not need the new release, take your time.

Thanks!

**Comment by klehmann** [comment]
Rewrote that code once more to reduce memory usage (57b6e6bb16f4b0b1e19bdca8442601045326535b), should still work :-).
