### ISSUE TITLE
Can I use this in a java web application?

### ISSUE THREAD

**Issue by windgaucho** [klehmann/domino-jna#23]
I wanted to know if I can use this project in a java web application ? (spring, java ee, etc).

**Comment by morexlt** [comment]
> I wanted to know if I can use this project in a java web application ? (spring, java ee, etc).

I am trying to use it too, can we have an example, or guide about how to import this in a running project. Please.
PS. Awesome project!

**Comment by klehmann** [comment]
That depends on the type of your project. Is it running inside a Domino server (XPages or OSGi servlet)?
You need to have access to the Notes/Domino DLLs where the API is running, so either on a machine with installed Notes Client or Domino server.

**Comment by windgaucho** [comment]
Actually, I have an application running like an OSGI servlet in a linux server, and I am using the ODA api.

So, I want to use spring and replace ODA with your project, that make sense?

**Comment by klehmann** [comment]
The easiest way would be to use Maven and add the following dependency to your project:

```xml
<dependency>
    <groupId>com.mindoo.domino</groupId>
    <artifactId>domino-jna</artifactId>
    <version>0.9.19</version>
</dependency>
````

That way you make sure to get all required dependencies and add them to your project.
(See https://mvnrepository.com/artifact/com.mindoo.domino/domino-jna for the latest available Domino JNA version)

Next, you wrap the code in your Servlet.service(HTTPServletRequest req, HTTPServletResponse response) method within a NotesGC.runWithAutoGC code block.

This automatically releases all allocated memory and C handles on completion.
For most cases, that should be enough, but if you iterate over a lot of Notes objects, you might call their recycle() method manually earlier, e.g. NotesNote.recycle() (note = document).

```java
//any code that creates the session or gets it from the DominoContext class
public void service((HTTPServletRequest req, HTTPServletResponse response)) throws ServletException {
	final Session session = this.createSession();

	NotesGC.runWithAutoGC(new Callable<Object>() {

		public Object call() throws Exception {
			//open database as the current session's effective user
			NotesDatabase dbData = new NotesDatabase(session, "MyServer/MyCompany", "path/to/db.nsf");
			//alternative: open database as a named user:
			//String userName = "Karsten Lehmann/Mindoo";
			//NotesDatabase dbData = new NotesDatabase("MyServer/MyCompany", "path/to/db.nsf", userName);
			//or as the current ID owner (e.g. the Domino server) if userName="" or null
				
			//open People view
			NotesCollection colFromDbData = dbData.openCollectionByName("People");

			// add code to work with Domino data here
			// ...

			return null;
		}
	});
}
```
