### ISSUE TITLE
Rich Text Field inline image

### ISSUE THREAD

**Issue by heekah7** [klehmann/domino-jna#28]
Hi Klehmann,

Thank you for the excellence library.

I notice that there's a problem in the original Domino Java API, where inline image cannot be retrieved. I am wondering can we read it with this great library? And can you give us a sample of doing it?

Regards

**Comment by klehmann** [comment]
I just uploaded a new sample. Is this what you were searching for?

https://github.com/klehmann/domino-jna/blob/master/domino-jna/src/test/java/com/mindoo/domino/jna/test/TestRichtextConversionToHTML.java

**Comment by heekah7** [comment]
Thanks for being extremely responsive, I will give it a good try!

Btw, thanks for the awesome library.
