### ISSUE TITLE
note.getUNID() returns NOTEID instead of UNID

### ISSUE THREAD

**Issue by eknori** [klehmann/domino-jna#3]
NotesNote.java line 142 ff

original:

`if (NotesJNAContext.is64Bit()) {
            notesAPI.b64_NSFNoteGetInfo(m_hNote64, NotesCAPI._NOTE_ID, retOid);
        } else {
            notesAPI.b64_NSFNoteGetInfo(m_hNote32, NotesCAPI._NOTE_ID, retOid);
        }`

must be :

`if (NotesJNAContext.is64Bit()) {
            notesAPI.b64_NSFNoteGetInfo(m_hNote64, NotesCAPI._NOTE_OID, retOid);
        } else {
            notesAPI.b64_NSFNoteGetInfo(m_hNote32, NotesCAPI._NOTE_OID, retOid);
        }`

**Comment by klehmann** [comment]
Thanks, fixed it!
