### ISSUE TITLE
Tab Table in RTF

### ISSUE THREAD

**Issue by heekah7** [klehmann/domino-jna#31]
![tabtable](https://user-images.githubusercontent.com/9999811/63849369-82fe7d00-c9c4-11e9-91d5-ccec090356c2.png)

convertItemToHtml works amazingly across all the item type, however I encounter some issue with Tab Table. When we are clicking on the other tab, it will be hyperlinked to file:///C:/personname2018.nsf?OpenField&TableRow=1.1#1.

Any idea?

**Comment by klehmann** [comment]
```com.mindoo.domino.jna.NotesNote.convertItemToHtml(String, EnumSet<HtmlConvertOption>``` has a second argument to control the HTML rendering.
Have you tried to use the value ```HtmlConvertOption. RowAtATimeTableAlt```?

The documentation says it improves rendering for tabbed tables by rendering all tabs.
BTW: I did a google search and just added a few more HTML conversion options.

See this commit for details: 4000c090c7fa6e831283ea8e5f541ad545ae4c5c

**Comment by heekah7** [comment]
You save me life again!

Thank you!

**Comment by klehmann** [comment]
I added two more options that you might want to try (haven't tested them yet): 9988b6d04fb392432b831b34a064fb4450c1dffc
