### ISSUE TITLE
Extract Attachment

### ISSUE THREAD

**Issue by heekah7** [klehmann/domino-jna#32]
I am currently extracting file like doc/excel via dataNote.getItems() then override the callback to retrieve all the document. Is it possible to extract attachment like images? I found it difficult to update the HTML reference string to the latest file path, unless using static which is not desirable. One issue with the reference link to the attachment is, if you have two attachment with the same name, the reference link will become /DBNAME/0/UNID/$File/ then without duplication only have the name test1.docx with duplication will turn the link to test1.001.docx/test1.docx.

On the other side, the IHtmlApiReference could not recognise the reference object as an attachment but just a HREF.

**Comment by klehmann** [comment]
Please send me your current implementation. Not sure what the problem is about and what you mean with „static“.

**Comment by heekah7** [comment]
Here is the file. Really thankful, I am not a Java pro, I use Java just for this library!

[Sample.txt](https://github.com/klehmann/domino-jna/files/3572917/Sample.txt)

**Comment by heekah7** [comment]
Just to clarify the problem is simply I am having issue replacing the original reference path to the current reference path. Hence, I am trying to do it in such a manner like image extraction and replace the original reference with the latest path.

**Comment by klehmann** [comment]
I rewrote the sample class so that it also extracts the attachments and replaces their href's.
Does this sample what you are searching for?
f94bb948d5cd5c37b2c78a5d9fdb8c48965836e0

**Comment by heekah7** [comment]
Thank Klehmann, it works!
One more challenge that I am facing would be collection, I use openCollectionByName() and provided the collection name to the function, can we get all the collections and loop through them instead of providing the collection name manually?

**Comment by klehmann** [comment]
I added ```NotesDatabase.getAllCollections()``` to read infos about all views from the design collection. Please take a look at https://github.com/klehmann/domino-jna/commit/ab502a75d61ae3e583f73798e84cee2976d09fb1 and e2e32b2790daf99693b9e13c3fbb92efaaa7a6c3

**Comment by heekah7** [comment]
Fantastic! Any chance I can get those changes as external library in .jar file?

**Comment by klehmann** [comment]
I published a new release today.

See this blog article:
https://www.mindoo.com/web/blog.nsf/dx/19092019172343KLEL3E.htm
