### ISSUE TITLE
does it support domino Notes 8.5

### ISSUE THREAD

**Issue by kenizhou** [klehmann/domino-jna#34]
Hello Klehmann,

 I would like to confirm if this library support Notes 8.5?
 We have encountered some JNA initialization error under Notes 8.5.

Thanks,
KeniZhou

**Comment by klehmann** [comment]
Hi!

you need at least R9.0.1. The errors you see are probably missing C functions in the nnotes.dll / libnotes.so.
For R10, I already added additional interfaces that can only be loaded on R10 servers (e.g. INotesNativeAPI64V1000 and INotesNativeAPI32V1000).
But I started developing Domino JNA on an 9.0.1 server, so I don't have a separation of C methods between 8.5.x and 9.
