### ISSUE TITLE
NotesCollection FTSearch

### ISSUE THREAD

**Issue by oshmianski** [klehmann/domino-jna#36]
Hello Klehmann,

1. How can i make FTSearch with NotesCollection?

I did:
`NotesDatabase dbData = new NotesDatabase...;
NotesCollection colFromDbData = dbData.openCollectionByName...;
String searchQuery = "error";
NotesFTSearchResult res = colFromDbData.ftSearch(searchQuery, 0, EnumSet.of(FTSearch.NUMDOCS_ONLY));`

But this ftSearch returns 0 num docs always.

2. Will the ftSearch work if the database is not built index (legacy will be)?

3. How to use the specific sorting when performing a ftSearch?

Can you give an examples?

Thanks

**Comment by klehmann** [comment]
Hi!

I did not get 0 entries as result when I just tried this with an empty EnumSet of FTSearch flags, but my search results did not appear in view order. Will need to do some tests to see how to change this and whether NUMDOCS_ONLY does not work as expected.

But I just created a (complicated) test case that does want you are searching for by running a FT search on the database, but restricted to the note ids contained in the view, and then reads the view data for the search matches in view order: 028151bf7929df00105b9508a600aea8bfaf95f5

Hope this helps. Will get back to you when I have more info

**Comment by klehmann** [comment]
I just added a second testcase to the class TestViewTraversalWithFTSearch that runs the FT search against the view index.
Looks like in this mode, results are either sorted by score, creation date or modified date.

So if you want custom sorting, I would recommend using the view selection as it is done in the first testcase.

**Comment by oshmianski** [comment]
Hi!

Thank you very match! The first example works perfectly.

But I'm a little surprised. The implementation is very different from the standard paradigm. This is unusual and some tricks are not obvious. Many undocumented functions are used.

I wrote a [small web application](https://codeby.net/threads/mt-log-web-chitalka.69027/) for reading various domino views. I used your library in it (version 0.44.0). Back-end is Open Source. You might be interested in looking at the implementation. It would be nice to hear your opinion.

Regards

**Comment by klehmann** [comment]
Looks good. One thing:
```
NotesDatabase dbData = new NotesDatabase(db.getServer(), db.getFilePath(), (String) null);
```
This opens the database as the server, not as the user. So if you are using reader fields in the documents, you might get unexpected results.
So either replace the null value with the username (canonical or abbreviated) or use the constructor that takes a lotus.domino.Session (the constructor then internally reads ```session.getEffectiveUsername()```).

**Comment by oshmianski** [comment]
Thanks.

Reading on behalf of the server was originally conceived (the craft is called so AdminReaders) :-))

I did not find how to get the current database (like legacy NotesSession.currentDatabase)?

Regards

**Comment by klehmann** [comment]
Since the API can also be used in standalone applications, there is no current database property yet, but I could probably add callbacks to get the current context (database/user) and implement them for the XPages environment to derive them from the HTTP request URL.

There already is IDUtils.setEffectiveUsername(), which stores the username for the current NotesGC block (for XPages = the current HTTP request), but I am not totally have with it. Just needed a place to store the user in my own apps.
It's possible that I refactor this and you need to change your code a bit on update. My current goal is to put as much functionality as possible into the API so that Notes.jar is not required anymore.

**Comment by oshmianski** [comment]
> There already is IDUtils.setEffectiveUsername(), which stores the username for the current NotesGC block (for XPages = the current HTTP request), but I am not totally have with it.

In my opinion, that is enough.
The Skope strategy is quite slippery, it seems to me.
