### ISSUE TITLE
Is it possible to open a local database?

### ISSUE THREAD

**Issue by glasen** [klehmann/domino-jna#37]
Hi,

currently i'm using the Domino Java API to open and extract e-mails from locally stored nsf-files.The Domino server is not running on my development system and i use "notes.jar" directly:

Here is some code which i use to open a nsf-file:

```
NotesThread.sinitThread();
Session session = NotesFactory.createSession();
Database db = this.session.getDatabase(null, filename, false);
List<View> views = this.db.getViews();
...
```
Is it possible to use "domino-jna" for local database-files? I've tried your sample application but i can't get it running.

**Comment by klehmann** [comment]
Hi! Sorry for the late response.

Here is a sample application to use Domino JNA locally: https://github.com/klehmann/domino-jna/blob/master/standalone-app-sample/src/main/java/com/mindoo/domino/jna/samples/standaloneapp/DominoJNAStandaloneSampleApp.java

**Comment by glasen** [comment]
After countless tries i got your sample code running. The important steps were to add the "notesIni"-path to my local PATH-variable and explicitly configure the Domino-server (Which i had not to do with the legacy-API).

**Comment by klehmann** [comment]
I would expect that adding the Notes.ini location to the PATH is not necessary if you set the -ini: command line parameter as described in the sample comment. But the Notes program directory must be in the PATH and also be set via -notesdir: parameter so that the dll/.so loading can work.
