### ISSUE TITLE
List of error codes

### ISSUE THREAD

**Issue by glasen** [klehmann/domino-jna#38]
What do the various error codes the exception "NotesError" throws mean? I'm getting for example the the error code "418" but i have no idea what this code means.

**Comment by klehmann** [comment]
As long as your code is already running, you can use 
`com.mindoo.domino.jna.errors.NotesErrorUtils.errToString(short)`

to convert the error code to a string.
Here is the text for error code 418:

Maximum number of memory segments that Notes can support has been exceeded - out of handles (error code: 418, raw error with all flags: 418)

The class `com.mindoo.domino.jna.errors.INotesErrorConstants` contains some error texts, but not all of them. Would probably be possible to run `errToString` in a loop to get them all.

**Comment by glasen** [comment]
Thank you for the quick answer. I will try the method tomorrow at work. Be this short message helps me a lot.

Another short question:

How do i prevent this error? My program should export documents from multiple NSF-files into a MongoDB-collection. Basically the program works but when i open multiple very big files (>10GB) in different parallel running threads i get the above error.

Do i have to "recycle" the "NotesData"-instances? I thought the NotesGC-class does the recycling for me.

**Comment by klehmann** [comment]
No, they don‘t, but there are less recycle() calls. For example reading view data calls NIFReadEntries internally which returns a 64k buffer of view data which I decode and throw away, no need for recycle() on view entries. And NotesTimeDate is just an int[2] internally.
But each NotesNote allocates a note handle and those are limited.
It‘s difficult to fix this in a consistent way. For example if I store the note id/UNID, close the handle after some time and reload it on demand, the doc returned might have been changed by someone else, resulting in mixed data for the application using the API.
One way could be to leverage Java garbage collection and trigger it more often, but that‘s not Java best practise and reduces overall performance.

**Comment by klehmann** [comment]
NotesGC.runWithAutoGC() currently only cleans up all collected handles and the end of the method.

**Comment by glasen** [comment]
I just added the recycling method to my NotesData-objects after processing them. Currently my program processes eight NSF-files in parallel and the bug is gone.

Many thanks for your help. Your library has helped me a lot.

**Comment by klehmann** [comment]
Thanks! Please note that I released 0.9.24 today which fixes an annoying bug in NotesNote.getItemValueString() / .getItemValueStringList() with values containing newlines (87865d4a8c7c5575fdd4bf2253c53cef08e5eda1).

Just want to make sure that you could read all data and not just part of it.
