### ISSUE TITLE
sysout statement left in MimeWriterUtil.writeStringToMIME

### ISSUE THREAD

**Issue by paulswithers** [klehmann/domino-jna#39]
https://github.com/klehmann/domino-jna/blob/master/domino-jna/src/main/java/com/mindoo/domino/jna/internal/mime/MimeWriterUtil.java#L336

**Comment by klehmann** [comment]
Thanks for the info, but that class is not done yet. That‘s why it is still in the internal package. It currently is only useful to produce broken and ugly emails. :-)
