### ISSUE TITLE
NotesViewEntryData getUNID() does not return UNID

### ISSUE THREAD

**Issue by eknori** [klehmann/domino-jna#5]
`viewEntry.getUNID()` 

is always **null**.  Also

`viewEntry.toString()`

does not include unid.  ( This works as designed in NotesViewEntryData ) :)

`		if (m_unid!=null) {
			sb.append(",unid="+m_unid);
		}`

**Comment by eknori** [comment]
my mistake. Forgot to setEnumSet<ReadMask> returnData = EnumSet.of(**ReadMask.NOTEUNID**, ...

**Comment by klehmann** [comment]
Right. UNID eats 16 bytes in the summary buffer while note ID only eats 4 bytes.
Changed the method NotesViewEntryData.toString() to return the UNID string even if it has not been computed yet from the long[] array. 1f371a8b8078aac047b3c5b9854ef60daad47601
