### ISSUE TITLE
Download Link for fakenames.nsf and fakenames-views.nsf invalid

### ISSUE THREAD

**Issue by sven-olding** [klehmann/domino-jna#56]
Good day! 

There is an error (HTTP 502) following the [download link](https://fs.mindoo.de/f/cd86250173344f18bce5/?dl=1) provided in README for the test databases

Kind regards
Sven

**Comment by klehmann** [comment]
Thanks. That server is currently not available. I updated the link.

**Comment by sven-olding** [comment]
Thank you!
