### ISSUE TITLE
Compilation error: cannot find symbol KFM_PASSWORDStruct

### ISSUE THREAD

**Issue by sven-olding** [klehmann/domino-jna#57]
I am getting some errors when building via mvn, apparently I am missing something? 
Cloned this from the current master branch... but I can´t see the mentioned class in package
com.mindoo.domino.jna.internal.structs

PS C:\domino-jna\domino-jna> mvn -DJVMPARAMS= -DDOMINOOSGIDIR="C:\Program Files (x86)\HCL\Notes\osgi" -DDOMINODIR="C:\Program Files (x86)\HCL\Notes" -DNOTESINI="C:\Program Files (x86)\HCL\Notes\notes.ini" clean install
[INFO] Scanning for projects...
[INFO]
[INFO] --------------------< com.mindoo.domino:domino-jna >--------------------
[INFO] Building Domino JNA 0.9.40
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ domino-jna ---
[INFO] Deleting C:\domino-jna\domino-jna\target
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ domino-jna ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 2 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ domino-jna ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 317 source files to C:\domino-jna\domino-jna\target\classes
[INFO] -------------------------------------------------------------
[WARNING] COMPILATION WARNING :
[INFO] -------------------------------------------------------------
[WARNING] /C:/domino-jna/domino-jna/src/main/java/com/mindoo/domino/jna/NotesSearch.java: Some input files use or override a deprecated API.
[WARNING] /C:/domino-jna/domino-jna/src/main/java/com/mindoo/domino/jna/NotesSearch.java: Recompile with -Xlint:deprecation for details.
[WARNING] /C:/domino-jna/domino-jna/src/main/java/com/mindoo/domino/jna/richtext/FieldInfo.java: Some input files use unchecked or unsafe operations.
[WARNING] /C:/domino-jna/domino-jna/src/main/java/com/mindoo/domino/jna/richtext/FieldInfo.java: Recompile with -Xlint:unchecked for details.
[INFO] 4 warnings
[INFO] -------------------------------------------------------------
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /C:/domino-jna/domino-jna/src/main/java/com/mindoo/domino/jna/utils/IDUtils.java:[23,46] cannot find symbol
  symbol:   class KFM_PASSWORDStruct
  location: package com.mindoo.domino.jna.internal.structs
[ERROR] /C:/domino-jna/domino-jna/src/main/java/com/mindoo/domino/jna/internal/INotesNativeAPI.java:[4,46] cannot find symbol
  symbol:   class KFM_PASSWORDStruct
  location: package com.mindoo.domino.jna.internal.structs
[ERROR] /C:/domino-jna/domino-jna/src/main/java/com/mindoo/domino/jna/internal/INotesNativeAPI.java:[485,43] package KFM_PASSWORDStruct does not exist
[ERROR] /C:/domino-jna/domino-jna/src/main/java/com/mindoo/domino/jna/internal/NotesNativeAPI64.java:[13,65] package com.mindoo.domino.jna.internal.structs.KFM_PASSWORDStruct does not exist
[ERROR] /C:/domino-jna/domino-jna/src/main/java/com/mindoo/domino/jna/internal/INotesNativeAPI64.java:[6,46] cannot find symbol
  symbol:   class KFM_PASSWORDStruct
  location: package com.mindoo.domino.jna.internal.structs
[ERROR] /C:/domino-jna/domino-jna/src/main/java/com/mindoo/domino/jna/internal/NotesNativeAPI64.java:[1528,69] cannot find symbol
  symbol:   class ByReference
  location: class com.mindoo.domino.jna.internal.NotesNativeAPI64
[ERROR] /C:/domino-jna/domino-jna/src/main/java/com/mindoo/domino/jna/internal/INotesNativeAPI64.java:[1833,43] package KFM_PASSWORDStruct does not exist
[ERROR] /C:/domino-jna/domino-jna/src/main/java/com/mindoo/domino/jna/internal/NotesNativeAPI.java:[25,65] package com.mindoo.domino.jna.internal.structs.KFM_PASSWORDStruct does not exist
[ERROR] /C:/domino-jna/domino-jna/src/main/java/com/mindoo/domino/jna/internal/NotesNativeAPI.java:[812,67] cannot find symbol
  symbol:   class ByReference
  location: class com.mindoo.domino.jna.internal.NotesNativeAPI

**Comment by klehmann** [comment]
Sorry, forgot that class in my recent commit. Just pushed it to Github, please retry.

**Comment by sven-olding** [comment]
Thank you! I just had a quick look at it and the problem with the missing KFM_PASSWORDStruct is resolved. But there is another error. I didn´t had the time to have a deeper look at it. 

[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /C:/domino-jna/domino-jna/src/test/java/com/mindoo/domino/jna/test/TestNamesListCreation.java:[11,33] package com.ibm.domino.napi.c.xsp does not exist
[ERROR] /C:/domino-jna/domino-jna/src/test/java/com/mindoo/domino/jna/test/TestNamesListCreation.java:[79,57] cannot find symbol
  symbol: variable XSPNative
[INFO] 2 errors

**Comment by klehmann** [comment]
Please run the compilation with ```-Dmaven.test.skip=true```. That specific test references classes of the XPages runtime that I have added manually in my Eclipse environment:
<img width="1025" alt="image" src="https://user-images.githubusercontent.com/4291861/97625812-4a738c80-1a29-11eb-94f4-b5ba7ddc6765.png">

**Comment by sven-olding** [comment]
Thanks, running without the tests resovled the issue!
