### ISSUE TITLE
Unexplainable performance issues

### ISSUE THREAD

**Issue by adiXSG** [klehmann/domino-jna#58]
I've built an OSGi plugin which runs on the Domino server and provides a JAX-RS REST API. Some operations must start existing LotusScript business logic in the context of the user which is done by calling an agent. This all works well but I have some unexplainable performance issues when using domino-jna in production. First issue was the initialization of domino-jna and I've moved it to the OSGi Activator and that's ok so far.

But I've still some performance issues. I've added trace logs and seen there getting a database or an agent can take up to 3...4 seconds. Another few seconds to create a note or attach attachments to it. Next time calling the same REST API endpoint the execution of the same operations which have taken multiple seconds before runs then within a few milliseconds. I have no idea what is taking so long to create a new note for example.

To show you the basics of what I've done I added the code snippet and a sample log of an execution below. As you see, the log below shows only a time gap when attaching files to the note. But as I sad, I've seen gaps in other logs like this while getting the database or getting the agent.

Do you have an idea what is causing this bad performance?

```
@Override
protected void executeAgent(String user) throws Exception {

	LOG.debug("Starting execute");

	try {
		LOG.trace("Starting domino-jna with auto GC processing");
		String prints = NotesGC.runWithAutoGC(() -> {

			LOG.trace("Getting database");
			NotesDatabase ndb = getDatabase(user);

			LOG.trace("Getting agent");
			NotesAgent ag = getAgent(ndb, user);

			LOG.trace("Create note");
			NotesNote note = ndb.createNote();

			for (Attachment attachment : files) {
				LOG.trace("Attach file {} to note", attachment.getFileName());
				note.attachFile(attachment, attachment.getFileName(), attachment.getCreated(), attachment.getModified());
			}

			for (Map.Entry<String, Object> param : params.entrySet()) {
				LOG.trace("Setting agent param {} with value {}", param.getKey(), param.getValue());
				note.replaceItemValue(param.getKey(), param.getValue());
			}

			LOG.trace("Prepare agent run context");
			Writer printWriter = new StringWriter();
			NotesAgentRunContext narc = new NotesAgentRunContext();
			narc.setDocumentContextAsNote(note);
			narc.setUsername(user);
			narc.setCheckSecurity(true);
			narc.setOutputWriter(printWriter);

			LOG.trace("Execute agent run");
			ag.run(narc);
			LOG.trace("Agent execution completed");

			note.update();

			return printWriter.toString();
		});
	} finally {
		LOG.debug("Agent execution completed");
	}
}
```

```
2020-10-30 09:53:46,539 DEBUG Starting execute
2020-10-30 09:53:46,539 TRACE Starting domino-jna with auto GC processing
2020-10-30 09:53:46,539 TRACE Getting database
2020-10-30 09:53:46,539 TRACE Getting agent
2020-10-30 09:53:46,539 TRACE Create note
2020-10-30 09:53:46,539 TRACE Attach file mailbody.html to note
2020-10-30 09:53:50,976 TRACE Setting agent param att_targetfield with value sys_attachment
2020-10-30 09:53:50,992 TRACE Setting agent param sys_bcid with value 1
....
```

**Comment by klehmann** [comment]
Hi!
What’s the Domino version and OS? Is this a local or remote database? And have you tried a similar call using Notes.jar and it is faster? Not sure what could be causing this. Never had that and I have Domino JNA running in production on multiple customer servers on Windows and Linux.

**Comment by adiXSG** [comment]
Hi Karsten and thank you very much for your response.

- Domino server version is 10.0.1 FP3
- Domino-JNA version is 0.9.20
- OS is Windows Server 2016.
- databases are local

In the same OSGi Plugin I use the Notes.jar also. There, I didn't see any performance like these mentioned.

**Comment by klehmann** [comment]
Not sure if this helps, but 0.9.20 is pretty old. Have you tried the latest version 0.9.39?
=> https://github.com/klehmann/domino-jna/releases/tag/0.9.39

**Comment by adiXSG** [comment]
OK... I will test it and post my findings afterwards

**Comment by adiXSG** [comment]
Unfortunately, I still can see some very slow operations like attach a file to a note which takes about 5,5s (file size 15kb).

```
2020-11-06 14:18:04,768 TRACE c.b.o.a.d.a.AbstractQuerySaveAgent [qtp-1628790797-123]: Attach file Defibrillator_Deckblatt_2011060958334840 (Recovered).docx to note
2020-11-06 14:18:10,002 TRACE c.b.o.a.d.a.AbstractQuerySaveAgent [qtp-1628790797-123]: Setting agent param att_targetfield with value Dok_Anhang
```

**Comment by klehmann** [comment]
Have you tried disabling the virus scanner if there is one running on the server? And could you check if it's only an issue on Windows or on Linux as well?
