### ISSUE TITLE
Sample of Get document fields

### ISSUE THREAD

**Issue by sattam-datum** [klehmann/domino-jna#59]
I need sample code to get document fields and how to convert rich text fields to html along with thier attachment and note that rich text might have inline images

**Comment by klehmann** [comment]
Here is an example for document loading (NotesNote) and richtext conversion to HTML:
https://github.com/klehmann/domino-jna/blob/master/domino-jna/src/test/java/com/mindoo/domino/jna/test/TestRichtextConversionToHTML.java

Regarding reading item values, there are several getItemValueXXX methods in the NotesNote class.

**Comment by sattam-datum** [comment]
It's  working fine thanks
