### ISSUE TITLE
Doc links are not generated after converting rich text to html

### ISSUE THREAD

**Issue by sattam-datum** [klehmann/domino-jna#60]
![image](https://user-images.githubusercontent.com/76649628/103197851-7c04b900-48ef-11eb-9163-2695db10c10d.png)

I am unable to find generated link for doc links, like the above screen shot

**Comment by klehmann** [comment]
Haven’t checked yet, but have you made sure the database contains a default view? Could be causing this kind of problem.

**Comment by sattam-datum** [comment]
It's not related to view, this doc link inside rich text in the document:

so as example rich text will contains like this :      Click here >>
![image](https://user-images.githubusercontent.com/76649628/103198730-be2efa00-48f1-11eb-9966-3621ddebd08e.png)

**Comment by klehmann** [comment]
I know. But have you checked that there is a default view in the design?

**Comment by sattam-datum** [comment]
Yes there is ,
also note that I don't have privilege to change anything.

**Comment by klehmann** [comment]
Ok. And there is no IMG tag at all for the doclink? I would expect it to be broken because it’s not a normal embedded image that can be extracted from the richtext CD records, but a shared icon resource. Will test it later today.

**Comment by sattam-datum** [comment]
It's standard style of lotus notes link :   below is sample the generated xml of it

<doclink document='8D4E93D5D4063234234324234' view='32432423423423'
 database='1234566' description='Database $$test;, View &apos;$$test &apos;, Document &apos;$$test &apos;'/>

**Comment by klehmann** [comment]
Some progress here. I also don't get doclinks when I use the richtext-html conversion with my local Notes Client, but it works when running on the Domino server (tried the XPages plugin on Domino R10 / R11).  Will need to ask HCL core dev if there are any settings I need to set to make it work locally as well.

**Comment by klehmann** [comment]
More progress. By setting a conversion property via HTMLSetProperty I can change the link handling behavior. Will be in the next version coming out soon.
Without the property:
```HTML
<font size="2" face="sans-serif">Doclink:</font><br>
<br>
<br>
<font size="2" face="sans-serif">View-Link:</font><br>
<br>
<br>
<font size="2" face="sans-serif">Db-Link:</font><br>
<br>
<br>
```

With the property set:
```HTML
<font size="2" face="sans-serif">Doclink:</font><br>
<a href="/__482571d7000a8bd1.nsf/862561bd0045e8e785255b3c105a57bb/afcb7236f22e8338482573fb00323555?Redirect&Name=Karstens-Mac.local"><img src="/icons/doclink.gif" border="0" alt="IBM C API Notes/Domino 9.0.1 Reference"></a><br>
<br>
<font size="2" face="sans-serif">View-Link:</font><br>
<a href="/__482571d7000a8bd1.nsf/862561bd0045e8e785255b3c105a57bb?Redirect&Name=Karstens-Mac.local"><img src="/icons/viewlink.gif" border="0" alt="IBM C API Notes/Domino 9.0.1 Reference"></a><br>
<br>
<font size="2" face="sans-serif">Db-Link:</font><br>
<a href="/__482571d7000a8bd1.nsf?Redirect&Name=Karstens-Mac.local"><img src="/icons/dblink.gif" border="0" alt="IBM C API Notes/Domino 9.0.1 Reference"></a><br>
```

Will be on by default but can be disabled.

**Comment by sattam-datum** [comment]
New update on this:
  some doc links are retuning in html like below but the href is not working
&lt;a href="/filepath.nsf/cbe588ea18299e4785257482004e5f55/42ac321cf12b96148525799900757db6?OpenDocument"&gt;&lt;img src="/icons/doclink.gif" border="0" alt="Testing"&gt;&lt;/a&gt;

and standard anchor generated and working fine like below:
8D4E93D5D4063E9985257D82005A9062
&lt;a href="Notes:///8525706F0068109E/5FA05CA50D3C2BF3852570FC00653E79"&gt;Notes Link&lt;/a&gt

this was tested on version 0.9.39

**Comment by klehmann** [comment]
FYI: The new Domino JNA version with advanced richtext-html conversion options is now available.

**Comment by sattam-datum** [comment]
can you provide us with the sample code of how to show the doc links in the generated html?

**Comment by klehmann** [comment]
Yes, sure:
https://github.com/klehmann/domino-jna/blob/master/domino-jna/src/test/java/com/mindoo/domino/jna/test/TestRichtextConversionToHTML.java#L80
