### ISSUE TITLE
replicate with Server

### ISSUE THREAD

**Issue by beranPro** [klehmann/domino-jna#75]
Hi,
i'm trying to replicate a DB via a Java app using Domino-JNA from a Windows PC with Notes client installed. I can open the Database without problem but when i'm calling replicateWithServer the NotesReplicationStats  looks like this:

He states that he's got some errors (numberErrors1)

`NotesReplicationStats [stubsInitialized=0, totalUnreadExchanges=0, numberErrors=1, pullTotalFiles=1, pullFilesCompleted=0, pullNotesAdded=0, pullNotesDeleted=0, pullSuccessful=1, pullFailed=1, pullNumberErrors=1, pushTotalFiles=0, pushFilesCompleted=0, pushNotesAdded=0, pushNotesDeleted=0, pushSuccessful=0, pushFailed=0, pushNumberErrors=0]`

And here the screenshot from debugging the object:
![image](https://user-images.githubusercontent.com/15611411/175880889-4eb1dcd8-fef8-4764-9fb9-9f2f7e11a2d4.png)

the path is "anwendungen/telefonbuch.nsf" and the server is in this style "SERVER01/notes"

```java
@Override
public boolean replicate(ReplicationClientRequest newReplication) {
    final boolean ret = false;
    EnumSet<ReplicateOption> replOptions = EnumSet.noneOf(ReplicateOption.class);
    replOptions.add(ReplicateOption.RECEIVE_NOTES);
    replOptions.add(ReplicateOption.SEND_NOTES);

    try {

        //initial Notes/Domino access for current thread (running single-threaded here)
        NotesThread.sinitThread();

        //launch run method within runWithAutoGC block to let it collect/dispose C handles
        NotesGC.runWithAutoGC(new Callable<Object>() {

            public Object call() throws Exception {
                boolean dontSetEnvVar = true;
                IDUtils.switchToId("C:\\Program Files (x86)\\HCL\\Notes\\Data\\user.id", "MySuperSecurePassword", dontSetEnvVar);

                NotesDatabase dbNames = new NotesDatabase("", newReplication.getPath(), "");
                NotesReplicationStats nrs = dbNames.replicateWithServer(newReplication.getServer(), replOptions, 5);
                logger.info("Nr of Errors %s and successfull %s", nrs.getNumberErrors(), nrs.getPullSuccessful());
                return new Object();
            }

        });
    } catch (Exception e) {
        throw new RuntimeException(e);
    } finally {
        //terminate Notes/Domino access for current thread
        NotesThread.stermThread();
    }
    return false;
}
´´´

**Comment by beranPro** [comment]
ok, now it works - maybe i had a typo somewhere...

- closed -

**Comment by klehmann** [comment]
Ok, great. BTW you can use the SignalHandlerUtil class to get replication progress details and to register a break handler and be able to cancel a long running operation like searches or replication.

https://github.com/klehmann/domino-jna/blob/master/domino-jna/src/main/java/com/mindoo/domino/jna/utils/SignalHandlerUtil.java#L353
